DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS company CASCADE;
DROP EXTENSION IF EXISTS pgcrypto;

CREATE EXTENSION pgcrypto;


CREATE TABLE company (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(200)        NOT NULL,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE contacts (
    id              UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
    created_date    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMP WITHOUT TIME ZONE         NULL,
    last_name       VARCHAR(50)                         NOT NULL,
    first_name      VARCHAR(50)                         NOT NULL,
    email           VARCHAR(50)                         NOT NULL,
    phone_number    VARCHAR(20)                         NULL,
    company         INTEGER                             NOT NULL,
    note            TEXT                                NULL,
    status          VARCHAR(10)                         NOT NULL
);

ALTER TABLE ONLY contacts
    ADD CONSTRAINT fk_contacts_company_id FOREIGN KEY (company) REFERENCES company(id);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

INSERT INTO contacts(last_name, first_name, email, company, status)
VALUES
        ('Példa', 'Béla', 'peldabela@gmail.com', 1, 'ACTIVE'),
        ('Git', 'Áron', 'gitaron@gmail.com', 2, 'DELETED'),
        ('Nagy', 'Martin', 'nagymartin@gmail.com', 3, 'ACTIVE'),
        ('Faragó', 'István', 'farago.istvan@gmail.com', 2, 'ACTIVE'),
        ('Vereti', 'Péter', 'veretipeter@citromail.com', 3, 'ACTIVE');
