DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS company CASCADE;
DROP EXTENSION IF EXISTS pgcrypto;
DROP TYPE IF EXISTS status_type;

CREATE EXTENSION pgcrypto;
CREATE TYPE status_type AS ENUM('ACTIVE', 'DELETED');


CREATE TABLE company (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(200)        NOT NULL,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE contact (
    id              UUID  PRIMARY KEY DEFAULT gen_random_uuid(),
    created_date    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMP WITHOUT TIME ZONE         NULL,
    last_name       VARCHAR(50)                         NOT NULL,
    first_name      VARCHAR(50)                         NOT NULL,
    email           VARCHAR(50)                         NOT NULL,
    phone_number    VARCHAR(20)                         NULL,
    company         INTEGER                             NOT NULL,
    note            TEXT                                NULL,
    status          status_type                         NOT NULL
);

ALTER TABLE ONLY contact
    ADD CONSTRAINT fk_contact_company_id FOREIGN KEY (company) REFERENCES company(id);

insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

INSERT INTO contact(last_name, first_name, email, company, status)
VALUES
        ('Pelda', 'Bela', 'peldabela@gmail.com', 1, 'ACTIVE'),
        ('Git', 'Aron', 'gitaron@gmail.com', 2, 'DELETED'),
        ('Nagy', 'Martin', 'nagymartin@gmail.com', 3, 'ACTIVE'),
        ('Farago', 'Istvan', 'farago.istvan@gmail.com', 2, 'ACTIVE'),
        ('Vereti', 'Peter', 'veretipeter@citromail.com', 3, 'ACTIVE');
